@API_HostAddress = http://localhost:5237/v1

GET {{API_HostAddress}}
Accept: application/json

###

GET {{API_HostAddress}}/address

###

GET {{API_HostAddress}}/address/robo_1

###

POST {{API_HostAddress}}/address
Content-Type: application/json


[
    {
        "CEP": "31680030"
    }
] 

###

PUT {{API_HostAddress}}/address
Content-Type: application/json

{
    "Id": 8,
    "CEP": "31680030",
    "Logradouro": "Rua Cricaré",
    "Bairro": "Maria Helena",
    "UF": "MG"
}
